### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by imtpalmer** [dedica-team/nivio#147] opened 2020-06-03 14:29 UTC
Made several attempts to build from source with no success. 

Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T11:06:16-04:00)
Maven home: /usr/local/Cellar/maven/3.6.2/libexec
Java version: 11.0.7, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
Python 3.8.3
Node v14.4.

..
[INFO] > nivio@0.3.0 test ../nivio/src/main/app
[INFO] > react-scripts test
[INFO] 
[ERROR] PASS src/Components/ModalComponent/GenericModal.test.tsx
[ERROR] PASS src/Components/LandscapeComponent/Landscape/Landscape.test.tsx
[ERROR] PASS src/Components/LandscapeComponent/Item/LandscapeItem.test.tsx
[ERROR] PASS src/Components/TitleBarComponent/TitleBar.test.tsx
[ERROR] PASS src/Components/LandscapeComponent/Log/LandscapeLog.test.tsx
[ERROR] PASS src/Components/ManComponent/Man.test.tsx
[ERROR] PASS src/Components/LevelChipComponent/LevelChip.test.tsx
[ERROR] PASS src/Components/LandscapeComponent/LandscapeOverview/LandscapeOverview.test.tsx
[ERROR] PASS src/Components/EventComponent/Events.test.tsx
[ERROR] PASS src/Components/NavigationComponent/Navigation.test.tsx
[ERROR] PASS src/App.test.tsx
[ERROR] 
[ERROR] Test Suites: 11 passed, 11 total
[ERROR] Tests:       13 passed, 13 total
[ERROR] Snapshots:   0 total
[ERROR] Time:        4.192s
[ERROR] Ran all test suites.
...

2020-06-03 10:01:04.226  INFO 78678 --- [lTaskExecutor-1] de.bonndan.nivio.input.DirectoryWatcher  : Starting directory watcher on /var/folders/qs/nzdk5fc50sj8stmdssmnvg6rz6qxp8/T
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.032 s <<< FAILURE! - in de.bonndan.nivio.input.DirectoryWatcherTest
[ERROR] testFileChange  Time elapsed: 2.022 s  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:
applicationEventPublisher.publishEvent(
    <Capturing argument>
);
-> at de.bonndan.nivio.input.DirectoryWatcherTest.testFileChange(DirectoryWatcherTest.java:45)
Actually, there were zero interactions with this mock.

	at de.bonndan.nivio.input.DirectoryWatcherTest.testFileChange(DirectoryWatcherTest.java:45)

[build.log](https://github.com/dedica-team/nivio/files/4724007/build.log)

**Comment by bonndan** [comment] 2020-06-03 15:04
Hi! Many thanks for the bug report.

Unfortunately we don't build on OS X automatically, so this bug never showed up so far.

You now can :

* try to ignore the test. Nivio will likely work except (maybe) when you try to change local configuration files on the fly
* try to fix the test (or @mfbieber will)
* open another issue to request publishing of jars
* try to extract the jar from a docker image release

**Comment by mfbieber** [comment] 2020-06-03 15:05
I will look into it today or tomorrow in the evening and try to provide a fix for MacOs.

**Comment by mfbieber** [comment] 2020-06-03 22:05
@imtpalmer : thanks again for submitting the bug report!

The failing test ist related to detecting changes in files. On my mac, I could reproduce your build failure too. It seems that the event is not being registered on time. So "simply" increasing the `Thread.sleep()` after modifying the file, makes the test pass.

I have a draft PR for that: https://github.com/dedica-team/nivio/pull/149

But I suggest that we don't merge that "fix" but provide a proper bugfix with a better implementation. Probably the changes in https://github.com/dedica-team/nivio/pull/148 (which will be merged in the next days) could also fix this problem. I will for sure check it out on my Mac too.

I hope this helps in making your build succeed now!

**Comment by bonndan** [comment] 2020-06-04 10:48
@imtpalmer pls. see if it works now

**Comment by imtpalmer** [comment] 2020-06-09 15:45
@bonndan I cloned develop and get the same results. 

2020-06-09 11:10:58.152  INFO 62222 --- [           main] o.e.jetty.server.handler.ContextHandler  : Stopped o.e.j.s.ServletContextHandler@283f8e50{/,null,UNAVAILABLE}
2020-06-09 11:10:58.153  INFO 62222 --- [           main] o.e.jetty.server.handler.ContextHandler  : Stopped o.e.j.s.ServletContextHandler@6a5b7fbc{/__admin,null,UNAVAILABLE}
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.163 s - in de.bonndan.nivio.output.LocalServerTest
[INFO] Running de.bonndan.nivio.assessment.StatusValueTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in de.bonndan.nivio.assessment.StatusValueTest
[INFO] Running de.bonndan.nivio.assessment.AssessmentFactoryTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 s - in de.bonndan.nivio.assessment.AssessmentFactoryTest
[INFO] Running de.bonndan.nivio.assessment.kpi.CustomKPITest
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s - in de.bonndan.nivio.assessment.kpi.CustomKPITest
[INFO] Running de.bonndan.nivio.assessment.kpi.ConditionKPITest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in de.bonndan.nivio.assessment.kpi.ConditionKPITest
[INFO] Running de.bonndan.nivio.assessment.kpi.ScalingKPITest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in de.bonndan.nivio.assessment.kpi.ScalingKPITest
[INFO] Running de.bonndan.nivio.assessment.AssessableTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in de.bonndan.nivio.assessment.AssessableTest
[INFO] Running de.bonndan.nivio.model.ItemTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in de.bonndan.nivio.model.ItemTest
[INFO] Running de.bonndan.nivio.model.ItemMatcherTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in de.bonndan.nivio.model.ItemMatcherTest
[INFO] Running de.bonndan.nivio.model.FullyQualifiedIdentifierTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in de.bonndan.nivio.model.FullyQualifiedIdentifierTest
[INFO] Running de.bonndan.nivio.model.LandscapeItemsTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in de.bonndan.nivio.model.LandscapeItemsTest
[INFO] Running de.bonndan.nivio.model.GroupsTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in de.bonndan.nivio.model.GroupsTest
[INFO] Running de.bonndan.nivio.model.LabelTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in de.bonndan.nivio.model.LabelTest
[INFO] Running de.bonndan.nivio.model.LandscapeConfigTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in de.bonndan.nivio.model.LandscapeConfigTest
[INFO] Running de.bonndan.nivio.model.LabeledTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in de.bonndan.nivio.model.LabeledTest
[INFO] Running de.bonndan.nivio.model.ItemFactoryTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.009 s - in de.bonndan.nivio.model.ItemFactoryTest
[INFO] Running de.bonndan.nivio.model.RelationTypeTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in de.bonndan.nivio.model.RelationTypeTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   DirectoryWatcherTest.testFileChange:46 
applicationEventPublisher.publishEvent(
    <Capturing argument>
);
Wanted 1 time:
-> at de.bonndan.nivio.input.DirectoryWatcherTest.testFileChange(DirectoryWatcherTest.java:46)
But was 6 times:
-> at de.bonndan.nivio.input.DirectoryWatcher.run(DirectoryWatcher.java:68)
-> at de.bonndan.nivio.input.DirectoryWatcher.run(DirectoryWatcher.java:68)
-> at de.bonndan.nivio.input.DirectoryWatcher.run(DirectoryWatcher.java:68)
-> at de.bonndan.nivio.input.DirectoryWatcher.run(DirectoryWatcher.java:68)
-> at de.bonndan.nivio.input.DirectoryWatcher.run(DirectoryWatcher.java:68)
-> at de.bonndan.nivio.input.DirectoryWatcher.run(DirectoryWatcher.java:68)


[INFO] 
[ERROR] Tests run: 186, Failures: 1, Errors: 0, Skipped: 3
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:25 min
[INFO] Finished at: 2020-06-09T11:10:59-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project nivio: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/tpalmer/ithaka-repository/nivio/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
2020-06-09 11:10:59.246  INFO 62222 --- [extShutdownHook] o.s.m.s.b.SimpleBrokerMessageHandler     : Stopping...
2020-06-09 11:10:59.246  INFO 62222 --- [extShutdownHook] o.s.m.s.b.SimpleBrokerMessageHandler     : BrokerAvailabilityEvent[available=false, SimpleBrokerMessageHandler [DefaultSubscriptionRegistry[cache[0 destination(s)], registry[0 sessions]]]]
2020-06-09 11:10:59.246  INFO 62222 --- [extShutdownHook] o.s.m.s.b.SimpleBrokerMessageHandler     : Stopped.
2020-06-09 11:10:59.246  INFO 62222 --- [extShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'taskExecutor'
2020-06-09 11:10:59.247  INFO 62222 --- [extShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'brokerChannelExecutor'
2020-06-09 11:10:59.251  INFO 62222 --- [extShutdownHook] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'messageBrokerTaskScheduler'
2020-06-09 11:10:59.251  INFO 62222 --- [extShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'clientOutboundChannelExecutor'
2020-06-09 11:10:59.251  INFO 62222 --- [extShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'clientInboundChannelExecutor'

**Closed** 2020-06-28 16:14 UTC
Labels: bug, osx

**Comment by mfbieber** [comment] 2020-07-26 20:50
@imtpalmer: Hi Thomas, I just tested the Build once again on a Mac OS and it seems to be working from the develop branch just fine. Could you check if it is working for you too now?
